### ISSUE TITLE
[TNG] Fehlermeldung nach Update auf neueste Version

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_checkbox#10]
Seit dem Update per Composer erhalte ich folgende Fehlermeldung:

Fatal error: Uncaught exception RuntimeException with message Filter setting type checkbox_published has no class defined. thrown in composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/LegacyFilterSettingTypeFactory.php on line 60

**Comment by discordier** [comment]
Should have been fixed a long time ago. Sorry for not telling here.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cboelter could you please have a final look at this and tell if your issue has been resolved?
