### ISSUE TITLE
Contao 3.3.7, aktuelles Metamodel -> Listview Checkbox Einstellung wird ignoriert

### ISSUE THREAD

**Issue by Znrl** [MetaModels/attribute_checkbox#11]
Soll heißen sobald ich eine Checkbox als Attribut hinzufüge wird mir ein zusätzliches Auge im Backend angezeigt. Unabhängig davon ob "Listviews checkbox" aktiviert ist oder nicht.

**Comment by discordier** [comment]
Ist das Attribut als published checkbox konfiguriert?

**Comment by Znrl** [comment]
Hm angehakt war es nicht aber es gab ein paar doppelte Einträge etc. in der Datenbank. Ich hab nochmal alles neu Aufgesetzt um es zu testen und da geht es. 
Muss mir nochmal anschauen was da schief gelaufen ist vtl. durch irgend ein Update. Scheint wohl nicht oder nicht direkt an Metamodels zu liegen.

**Comment by discordier** [comment]
Doppelte Eintraege? In welcher Tabelle und welcher Art?

**Comment by Znrl** [comment]
Ich kam noch nicht dazu mir das genauer anzuschauen es ist aber nicht nur Metamodels es sieht eher so aus als wäre alles nochmal zusätzlich angelegt worden, abgesehen von einer Erweiterung, die ich erst vor kurzem installiert hab. Also nicht auf Metamodels beschränkt.

Wird das gecached? Ich hab jetzt nochmal alles gelöscht inkl. Browser Chache etc. und jetzt geht es auch in er Installation, in der der Fehler war.
Außerdem wurde da auch überall ein suffix an die Tabellen angehängt. Da sollte es sowieso nur die richtigen Tabellen nehmen. Wobei ich nicht weiß wie das mit den angelegten Metamodels Tabellen "mm_name" ist.

Mir ist jetzt nur noch ne Kleinigkeit aufgefallen.
Wenn eine Checkbox angehakt ist wird in den Contao Details (Ausrufezeichen im blauen Kreis) eine "1" angezeigt, ist es nicht angehakt erscheint:
 	"Unexpected behaviour, attribute new_book text representation was not rendered."
Könnte man noch abfangen.

Bin grad etwas im Zeitdruck, deshalb kann ich jetzt da nicht genauer schauen vtl. komm ich nächste Woche oder so nochmal dazu.

**Comment by discordier** [comment]
Alles klar, dann mach ich das hier mal zu.
Wenn du dann nochmal dazu gekommen bist, kannst du es gerne wieder aufmachen.
