### ISSUE TITLE
Aktivierung von Filterbar führt nur zu "1" oder "Leerzeichen"

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/attribute_checkbox#14]
Ich habe die Checkbox für die Online Funktion verwendet.
Aktiviere ich nun die Funktion "Filterbar" führt dies im Backend dazu, dass ich nur eine "1" auswählen kann. Man kann keine Auswahl zwischen "Online" und "Nicht Online" auswählen.

![metamodels_filterfehler](https://cloud.githubusercontent.com/assets/1218347/10801263/e0e947c8-7db6-11e5-9f29-ad83dc16b82a.jpg)

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/attribute_checkbox/commit/d297bf85461df4e0434ccc4ebc32ad7fbaa82257
