### ISSUE TITLE
Toggle Icon in Backend Listview funktioniert nicht bei Icon Namen mit Leerzeichen

### ISSUE THREAD

**Issue by bopsoid** [MetaModels/attribute_checkbox#28]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_checkbox/issues?q=is%3Aissue

## My environment is:

Classic LAMP-System under CentOS 7.7

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.3.16       |                                  |
| Contao version:                     |    4.4.8      |                                  |
| MetaModels version:                 |    2.1.x      |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |   bundle_all       |                                  |

## Issue description

Wenn man für eigene Toggle-Icons einer Checkbox in der Backend-Listview von MetaModels Icons auswählt, die z.B. Leerzeichen im Namen haben, so funktioniert das Umschalten nicht mehr. Weder ändert sich das Icon, noch wird in der Datenbank der Wert geändert.

## Steps to reproduce

1. Neues Checkbox Feld erstellen und eigene Toggle-Icons definieren
2. Als Toggle-Icons Dateien mit Leerzeichen im Dateinamen wählen
3. Vollständigen Prozess durchführen, um die Checkbox in das Metamodel zu integrieren, so dass das Icon im Backend Listview angezeigt wird
4. Auf das Icon klicken

## Describe the behaviour of the application

Das Icon wechselt nicht und die Datenbank wird nicht aktualisiert. Es kommt KEIN JS-Fehler im Browser.

## Describe the expected behaviour of the application

Icons sollte zwischen beiden Zuständen wechseln und die DB entsprechend aktualisiert werden.

Der Fehler ist mir zufällig aufgefallen. Normalerweise achte ich strikt darauf, dass Dateinamen KEINE Leerzeichen, Umlaute, Sonderzeichen etc. enthalten. Diesmal habe ich aus einer externen Quelle zwei PNG-Dateien für die Icons genommen und nicht auf die Dateinamen geachtet. Als dann das Togglen nicht klappte habe ich verzweifelt nach der Ursache gesucht, zumal ein anderes Toggle-Icon problemlos funktionierte. Bis mir das mit dem Dateinamen aufgefallen ist. Einfügen eines simplen Unterstrichs im Dateinamen löste das Problem.

Sorry, bin nicht sicher, ob das hier beim richtigen Modul steht (attribute_checkbox) oder ob es woanders hingehört (core, dc_general etc.). Bitte im Fall der Fälle verschieben, falls möglich.

**Comment by discordier** [comment]
Should solve itself when #23 is implemented.

**Comment by zonky2** [comment]
fixed in MM 2.2

**Comment by zonky2** [comment]
Fixed in DCG https://github.com/contao-community-alliance/dc-general/pull/561
