### ISSUE TITLE
Weitere checkboxen über die Listenansicht steuerbar machen

### ISSUE THREAD

**Issue by cogizz** [MetaModels/attribute_checkbox#3]
Es wäre cool, wenn man in der Listenansicht neben der Toggle-Funktion noch weitere Checkbox-Attribute steuern könnte. Wir haben zum Beispiel ähnlich wie bei den News eine Checkbox für "hervorheben" und da wäre es gut, wenn man das direkt in der Listenansicht machen könnte.

Ich könnte versuchen einen entsprechenden PR zu erstellen ... besteht da grundsätzlich Interesse dran?

**Comment by xantippe** [comment]
Test in MM core 2.0.0-alpha8

![shot42](https://cloud.githubusercontent.com/assets/1045318/12165322/3b9fde78-b51d-11e5-819d-1cbbd9cafffd.jpg)

lediglich die (deutsche) Bezeichnung bei der Attributeinstellung ist "verwirrend"
